name: Build hashcat
env:
      INCLUDE_PATHS: |
        charsets/
        docs/
        extra/
        layouts/
        masks/
        modules/
        OpenCL/
        rules/
        bridges/
        Python/
        tools/*.py
        tools/*.pl
        tunings/
        example*
        hashcat*
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'
  push:
    branches:
      - "*"  
    paths:
      - '.github/workflows/build.yml'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 make git zstd python3-dev cmake p7zip-full

      - name: Clone Source Code
        run: |
          git clone https://github.com/hashcat/hashcat
          git clone https://github.com/win-iconv/win-iconv

      - name: Compile and Install win-iconv
        run: |
          cd win-iconv/
          cmake -D WIN_ICONV_BUILD_EXECUTABLE=OFF -D CMAKE_INSTALL_PREFIX=/opt/win-iconv-64 -D CMAKE_CXX_COMPILER=$(which x86_64-w64-mingw32-g++) -D CMAKE_C_COMPILER=$(which x86_64-w64-mingw32-gcc) -D CMAKE_SYSTEM_NAME=Windows
          sudo make install
          cd ../

      - name: Install Windows Python
        run: |
          wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-python-3.12.10-1-any.pkg.tar.zst
          sudo mkdir /opt/win-python
          sudo tar --zstd -xf mingw-w64-x86_64-python-3.12.10-1-any.pkg.tar.zst -C /opt/win-python

      - name: Build hashcat
        run: |
          cd hashcat/
          make -j$(nproc) win

      - name: Get Hashcat Version String
        id: get_version
        run: |
          cd hashcat/
          VERSION_STRING=$(git describe --tags --always)
          echo "version=${VERSION_STRING}" >> $GITHUB_OUTPUT

      - name: Package Release Artifact
        id: package_release
        run: |
          cd hashcat/
          ARCHIVE_NAME="hashcat_${{ steps.get_version.outputs.version }}.7z"
          7z a ../$ARCHIVE_NAME $(echo "${{ env.INCLUDE_PATHS }}" | tr '\n' ' ')
          echo "archive_path=./$ARCHIVE_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.package_release.outputs.archive_path }}
          name: hashcat ${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.version }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
