name: Build

env:
  include_paths: |
    charsets/
    docs/
    extra/
    layouts/
    masks/
    modules/
    OpenCL/
    rules/
    example*
    hashcat*
    libhashcat*

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - 'OpenCL/**.h'
      - 'OpenCL/**.cl'
      - 'include/**.h'
      - 'src/**.c'
      - 'tools/**'
      - '**/Makefile'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'OpenCL/**.h'
      - 'OpenCL/**.cl'
      - 'include/**.h'
      - 'src/**.c'
      - 'tools/**'
      - '**/Makefile'
      - '.github/workflows/build.yml'

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        shared: [0, 1]
    name: Build Linux (${{ matrix.shared == 0 && 'Static' || 'Shared' }})
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          SHARED: ${{ matrix.shared }}
        run: |
          sudo apt install gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 make git
          git clone https://github.com/hashcat/hashcat
          git clone https://github.com/win-iconv/win-iconv
          cd win-iconv/
          patch < ../hashcat/tools/win-iconv-64.diff
          sudo make install
          cd ../
          make win
      - name: Generate artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hashcat-linux-${{ matrix.shared == 0 && 'static' || 'shared' }}
          path: ${{ env.include_paths }}
