name: Run Hashcat Password Recovery

on:
  workflow_dispatch:
  push:
    branches:
      - "*"  
    paths:
      - '.github/workflows/crack.yml'

jobs:
  hashcat-crack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full ocl-icd-opencl-dev clinfo
          
      - name: Download hashcat
        run: |
          wget https://github.com/hashcat/hashcat/releases/download/v7.0.0/hashcat-7.0.0.7z -O hashcat.7z
          
      - name: Extract hashcat
        run: |
          7z x hashcat.7z -ohashcat -y
          mkdir -p hashcat
          7z x hashcat.7z -ohashcat_temp -y
          # 自动检测首层目录名
          first_dir=$(find hashcat_temp -mindepth 1 -maxdepth 1 -type d | head -n 1)
          mv "$first_dir"/* hashcat/
          rm -rf hashcat_temp
          
      - name: Run hashcat command
        run: |
          cd hashcat
          chmod +x ./hashcat.bin
          ./hashcat.bin -I
          
